import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
const vazir = Vazirmatn({ subsets: ["arabic"] });
export const metadata: Metadata = {
  title: "Admin-Dashboard",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazir.className}>{children}
        <div className="flex justify-between">
        <div className="w-11/12 h-[50px] border-solid border-2 border-black ">jhhj</div>
        <div className="w-1/12 h-[100vh] border-solid border-2 border-black ">khk</div>
        </div>
      </body>
    </html>
  );
}